name: Keep Alive

on:
  workflow_dispatch:
  
  schedule:
    - cron: 0 0 */30 * *

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Keep Alive
        run: date > .github/KEEP
      - name: Commit
        uses: autosuite/autocommit@main
        with:
          commit-message: Keep Alive
          add-options: -A
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.REPO_TOKEN }}