name: Update from upstream

on:
  push:
    branches: 
      - mod
  schedule:
    - cron: "0 * * * *"

jobs:
  update:
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Update from upstream
      run: |
        u_commit=$(curl -s -N https://api.github.com/repos/iwestlin/gd-utils/commits | grep -o '[0-9a-z]\{40\}' | head -n 1 | cut -c1-7)
        [ $u_commit ] && sed -i "s/UPSTREAM_COMMIT=[0-9a-z]\{7\}/UPSTREAM_COMMIT=$u_commit/g" Dockerfile
    - uses: autosuite/autocommit@main
      with:
        commit-message: Update gd-utils
        add-options: -A
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.REPO_TOKEN }}
        branch: mod
