name: Update from upstream

on:
  push:
    branches: 
      - mod
  schedule:
    - cron: "0 */6 * * *"

jobs:
  update:
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.REPO_TOKEN }}
    - name: Update from upstream
      run: |
        u_commit=$(curl -s -N https://api.github.com/repos/iwestlin/gd-utils/commits | grep -o '[0-9a-z]\{40\}' | head -n 1 | cut -c1-7)
        [ $u_commit ] && sed -i "s/UPSTREAM_COMMIT=[0-9a-z]\{7\}/UPSTREAM_COMMIT=$u_commit/g" Dockerfile
    - name: Push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update gd-utils
        skip_dirty_check: false
